export const siteSettings = {
  id: 1,
  site_name: 'Rebase',
  tagline: '由中国开发者业余时间共同建立的非营利开发者社区',
  description:
    'Rebase Community 是由中国开发者们在业余时间用热爱建立的非营利、公益性开发者社区，持续组织 GeekDaily、Who-Is-Hiring、活动、文章与协作项目。',
  primary_domain: 'https://rebase.network',
  secondary_domain: 'https://rebase.community',
  media_domain: 'https://media.rebase.network',
  hero_title: 'Rebase Community 是由中国开发者们在业余时间用热爱建立的开发者社区。',
  hero_summary:
    '我们是非营利、公益性的开发者社区，持续组织 GeekDaily、Who-Is-Hiring、活动、文章与协作项目，让社区交流、机会与长期记录都有稳定入口。',
  hero_primary_cta_label: '进入 GeekDaily',
  hero_primary_cta_url: '/geekdaily',
  hero_secondary_cta_label: '查看招聘板',
  hero_secondary_cta_url: '/who-is-hiring',
  social_links: [
    { label: 'B 站', href: 'https://space.bilibili.com/382886213' },
    { label: 'YouTube', href: 'https://www.youtube.com/@rebasecommunity' },
    { label: 'Discord', href: 'https://discord.gg/9BATkxjfXS' },
    { label: 'Twitter', href: 'https://x.com/RebaseCommunity', handle: '@RebaseCommunity' },
    { label: 'Telegram', href: 'https://t.me/rebasenetwork', handle: '@rebasenetwork' },
    { label: 'GitHub', href: 'https://github.com/rebase-network' },
    { label: '微信公众号', href: 'https://mp.weixin.qq.com/', handle: 'rebase_network' },
    { label: 'QQ 群', href: 'https://qm.qq.com/', handle: '1001507060' },
  ],
  footer_groups: [
    {
      title: '社区项目',
      slug: 'community-projects',
      links: [
        { label: 'Web3Camp', href: 'https://web3camp.us' },
        { label: 'Rebase D. Ventures', href: 'https://rebased.ventures' },
        { label: 'Rebase Hackathon', href: 'https://github.com/rebase-network/work-groups/blob/main/README.md#rebase-hackathon' },
        { label: 'Web3 极客日报', href: 'https://github.com/rebase-network/work-groups/blob/main/README.md#web3极客日报' },
        { label: 'Who is hiring', href: 'https://github.com/rebase-network/who-is-hiring' },
        { label: 'Event Pool', href: 'https://github.com/rebase-network/event-pool' },
        { label: '社区福利', href: 'https://github.com/rebase-network/benefits' },
      ],
    },
    {
      title: '站点入口',
      slug: 'site-entry',
      links: [
        { label: 'About Rebase', href: '/about' },
        { label: 'GeekDaily', href: '/geekdaily' },
        { label: 'Articles', href: '/articles' },
        { label: 'Who-Is-Hiring', href: '/who-is-hiring' },
        { label: 'Events', href: '/events' },
        { label: 'Contributors', href: '/contributors' },
        { label: 'RSS', href: '/rss.xml' },
      ],
    },
    {
      title: '社区渠道',
      slug: 'community-channels',
      links: [
        { label: 'B 站', href: 'https://space.bilibili.com/382886213' },
        { label: 'YouTube', href: 'https://www.youtube.com/@rebasecommunity' },
        { label: 'Discord', href: 'https://discord.gg/9BATkxjfXS' },
        { label: 'Twitter', href: 'https://x.com/RebaseCommunity' },
        { label: 'Telegram', href: 'https://t.me/rebasenetwork' },
      ],
    },
    {
      title: '协作与资源',
      slug: 'resources',
      links: [
        { label: '协作文档', href: 'https://shimo.im/space/loqeMGmL7wiMgvqn' },
        { label: '媒体资源', href: 'https://github.com/rebase-network/media-kit' },
        { label: 'GitHub', href: 'https://github.com/rebase-network' },
        { label: '社区网站', href: 'https://rebase.network' },
      ],
    },
  ],
  home_signals: [
    {
      eyebrow: 'community brief',
      title: '这是一个由中国开发者用业余时间共同维护的非营利社区。',
      summary: 'Rebase Community 以公益性和长期主义为前提，为开发者持续提供交流、发布和连接的公共场所。',
      href: '/about',
      meta: 'non-profit community',
    },
    {
      eyebrow: 'geekdaily',
      title: 'Web3 极客日报是 Rebase 最稳定的持续发声机制。',
      summary: '每天更新的极客日报，把社区推荐、工具、研究和信号组织成可搜索、可订阅的长期档案。',
      href: '/geekdaily',
      meta: 'daily archive',
    },
    {
      eyebrow: 'opportunities',
      title: 'Who-Is-Hiring、Event Pool 和社区福利让机会线索长期可见。',
      summary: '我们希望读者一进入首页，就知道社区最近在写什么、做什么、开放了哪些机会。',
      href: '/who-is-hiring',
      meta: 'community opportunities',
    },
  ],
  home_stats: [
    { value: '1809+', label: '极客日报期数' },
    { value: '5458+', label: '极客日报推荐条目' },
    { value: '7', label: '长期协作栏目' },
  ],
  copyright_text: 'Copyright © Rebase Community. All rights reserved.',
};

export const aboutPage = {
  id: 1,
  title: 'Rebase Community 是由中国开发者们在业余时间用热爱建立的开发者社区。',
  summary:
    'Rebase Community 是非营利、公益性的开发者社区，专注于技术交流，并持续通过多个栏目和协作板块为开发者提供交流、发布与连接的场所。',
  sections: [
    {
      title: '我们是谁',
      body:
        'Rebase Community 是由中国开发者们在业余时间用热爱建立的开发者社区。\n\n我们坚持非营利、公益性的社区方向，专注技术交流，并希望把社区中的内容、协作和机会组织成长期可访问的公共入口。',
    },
    {
      title: '社区栏目与项目',
      body:
        '- [Web3Camp](https://web3camp.us)\n- [Rebase D. Ventures](https://rebased.ventures)\n- [Rebase Hackathon](https://github.com/rebase-network/work-groups/blob/main/README.md#rebase-hackathon)\n- [Web3 极客日报](https://github.com/rebase-network/work-groups/blob/main/README.md#web3极客日报)\n- [Who is hiring](https://github.com/rebase-network/who-is-hiring)\n- [Event Pool](https://github.com/rebase-network/event-pool)\n- [社区福利](https://github.com/rebase-network/benefits)',
    },
    {
      title: '社区入口与联系',
      body:
        '- 网站：https://rebase.network\n- B 站：https://space.bilibili.com/382886213\n- YouTube：https://www.youtube.com/@rebasecommunity\n- 微信公众号：**rebase_network**\n- QQ 群：**1001507060**\n- [Discord](https://discord.gg/9BATkxjfXS)\n- [Twitter](https://x.com/RebaseCommunity)\n- [Telegram](https://t.me/rebasenetwork)\n- [协作文档](https://shimo.im/space/loqeMGmL7wiMgvqn)\n- [媒体资源](https://github.com/rebase-network/media-kit)',
    },
    {
      title: '捐赠支持',
      body:
        'Rebase 社区当前接受捐赠，多签地址如下：\n\n- Ethereum：`0xC8ecB38d26205BCeec31310806FA5e29F7426ADb`\n- Polygon：`0x843BF7AdEbCe362a9Dbb42a8bD460f4bE0f6ccBD`',
    },
  ],
};

export const contributorRoles = [
  {
    slug: 'volunteers',
    status: 'published',
    name: '志愿者',
    description: '推动活动、内容和社区协调工作的人。',
  },
  {
    slug: 'geekdaily-advisors',
    status: 'published',
    name: '极客日报智囊团',
    description: '持续提供选题、推荐和行业感知的朋友们。',
  },
];

export const articles = [
  {
    slug: 'building-rebase-in-public',
    status: 'published',
    title: '把 Rebase 做成一个持续更新的社区媒体站点',
    summary: '为什么我们不只想做一个静态官网，而是想把社区日常真正组织成可阅读、可订阅、可回看的公共空间。',
    body: `## 重新定义社区站点\n\n传统社区官网往往更像公告栏，而不是一个持续更新的信息场。\n\nRebase 新站希望把 **GeekDaily、文章、活动、招聘、贡献者** 放到同一个阅读流里，让读者能在一次访问中看到社区最近发生了什么。\n\n## 为什么要重做\n\n- 旧结构无法很好承接持续更新的内容\n- GeekDaily 的历史规模已经足够大，需要新的信息架构\n- Who-Is-Hiring 需要比 issue 更稳定的公开落点\n\n## 我们想保留什么\n\n我们并不是想把社区变成一套复杂产品，而是想让内容更容易发现、传播与回看。`,
    published_at: '2026-04-05T10:00:00.000Z',
    reading_time: '7 min read',
    authors: [{ name: 'Ruix', role: 'Community steward' }],
    tags: ['community', 'product', 'media'],
    cover_image_url: null,
    cover_accent: 'linear-gradient(135deg, #efc37b 0%, #0f766e 100%)',
  },
  {
    slug: 'signal-over-noise',
    status: 'published',
    title: '社区信息不是越多越好，而是越有组织越好',
    summary: '在高频更新的内容环境里，真正重要的是信息架构，而不是堆更多入口。',
    body: `## Signal over noise\n\n社区运营并不是简单地发布更多内容，而是把内容组织成可以连续阅读的结构。\n\n当一个网站同时承接文章、招聘、活动和日报时，首页应该扮演 **signal desk** 的角色。\n\n## 一个好首页的标准\n\n1. 让新读者在 10 秒内理解 Rebase 是什么\n2. 让老读者快速看到今天的变化\n3. 让运营同学不需要手动维护太多重复内容`,
    published_at: '2026-04-02T08:30:00.000Z',
    reading_time: '5 min read',
    authors: [{ name: 'Cedric', role: 'Contributor' }],
    tags: ['information architecture', 'editorial'],
    cover_image_url: null,
    cover_accent: 'linear-gradient(135deg, #f7b267 0%, #f4845f 100%)',
  },
  {
    slug: 'community-archives-should-stay-readable',
    status: 'published',
    title: '社区档案不该只存在于 issue 和聊天记录里',
    summary: '当内容积累到一定规模，归档、搜索和订阅就不再是“加分项”，而是基础设施。',
    body: `## 档案感\n\n很多社区都拥有大量高质量内容，但这些内容往往缺乏统一的入口。\n\nRebase 新站会把历史 GeekDaily、公开文章和招聘信息重新组织成可搜索、可浏览、可订阅的结构。\n\n## 这意味着什么\n\n- URL 需要稳定\n- 搜索需要可用\n- RSS 需要成为标准输出\n- 旧内容也应该被新的访问者看见`,
    published_at: '2026-03-28T12:00:00.000Z',
    reading_time: '6 min read',
    authors: [{ name: 'Harry', role: 'Editor' }],
    tags: ['archives', 'rss', 'search'],
    cover_image_url: null,
    cover_accent: 'linear-gradient(135deg, #5cc8ff 0%, #4361ee 100%)',
  },
];

export const jobs = [
  {
    slug: 'protocol-growth-lead',
    status: 'published',
    company_name: 'Open Protocol Studio',
    role_title: 'protocol growth lead',
    salary: '$4,500 - $7,500 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / shanghai friendly',
    summary: '寻找熟悉开发者社区、内容运营和 protocol narrative 的增长负责人。',
    description: `## 岗位说明\n\n我们希望你能够在协议团队、开发者社区和内容传播之间建立顺畅协作。\n\n## 你会负责\n\n- 设计增长叙事\n- 对接活动与合作伙伴\n- 搭建长期内容分发节奏\n- 推动协议与社区叙事协同\n- 维护内容节奏和活动节奏\n- 与研究、开发和设计角色共同工作`,
    apply_url: 'https://example.com/jobs/protocol-growth-lead',
    apply_note: '请附上你主导过的社区、内容或增长案例。',
    contact_label: 'telegram',
    contact_value: '@rebase_hiring',
    published_at: '2026-04-04T09:00:00.000Z',
    expires_at: null,
    tags: ['growth', 'community', 'remote'],
  },
  {
    slug: 'community-editor',
    status: 'published',
    company_name: 'Builder Commons',
    role_title: 'community editor',
    salary: '$3,000 - $5,000 / month',
    supports_remote: true,
    work_mode: 'part-time',
    location: 'remote',
    summary: '负责社区写作、日报编排和专题策划，让内容从“发布”变成“持续阅读”。',
    description: `## 我们想找的人\n\n你不一定是专业媒体编辑，但需要对技术社区有长期观察，也愿意把复杂信息整理得更易读。\n\n## 方向\n\n- 日报整理\n- 专题写作\n- 站点栏目维护\n- 编辑文章与日报\n- 协调投稿与栏目排期\n- 优化内容展示和订阅体验`,
    apply_url: 'https://example.com/jobs/community-editor',
    apply_note: '欢迎附上你的文章、newsletter 或公开写作样本。',
    contact_label: 'email',
    contact_value: 'jobs@rebase.network',
    published_at: '2026-04-01T08:00:00.000Z',
    expires_at: null,
    tags: ['editorial', 'media', 'remote'],
  },
  {
    slug: 'frontend-engineer-community-platform',
    status: 'published',
    company_name: 'Rebase Studio',
    role_title: 'frontend engineer',
    salary: '$5,000 - $8,500 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / china time zone preferred',
    summary: '负责社区站点、内容产品和数据展示模块的前端实现。',
    description: `## 你会参与\n\n- 社区网站体验优化\n- 内容系统前台实现\n- 搜索、订阅和信息归档模块\n- 实现 Astro 前端体验\n- 协同 CMS 数据接入\n- 完善测试与发布流程\n\n## 我们看重\n\n对 UI 细节、信息组织和前端工程质量的平衡能力。`,
    apply_url: 'https://example.com/jobs/frontend-engineer-community-platform',
    apply_note: '请附上你主导或深度参与过的前端项目。',
    contact_label: 'wechat',
    contact_value: 'rebase-jobs',
    published_at: '2026-03-30T10:00:00.000Z',
    expires_at: null,
    tags: ['frontend', 'astro', 'community'],
  },
];

export const events = [
  {
    slug: 'rebase-shanghai-builder-night',
    status: 'published',
    event_status: 'upcoming',
    title: 'Rebase Shanghai Builder Night',
    summary: '一次围绕 AI tools、protocol research 和 community tooling 的小型夜间聚会。',
    content: `## 活动内容\n\n我们会邀请社区成员分享最近在做的工具、研究和协作方式。\n\n## 适合谁来\n\n- builder\n- editor\n- operator\n- 对社区产品感兴趣的人`,
    start_at: '2026-04-18T11:30:00.000Z',
    end_at: '2026-04-18T14:30:00.000Z',
    location: 'Shanghai',
    venue: 'West Bund community space',
    city: 'shanghai',
    registration_url: 'https://example.com/events/rebase-shanghai-builder-night',
    registration_note: '报名请先填写外部表单，我们会在活动前一天统一确认。',
    cover_image_url: null,
    tags: ['offline', 'builder', 'shanghai'],
  },
  {
    slug: 'geekdaily-editor-roundtable',
    status: 'published',
    event_status: 'upcoming',
    title: 'GeekDaily Editor Roundtable',
    summary: '围绕 GeekDaily 的选题、结构和订阅体验，做一次运营和编辑侧的公开讨论。',
    content: `## 讨论方向\n\n- 一期 GeekDaily 该如何被组织\n- 搜索和 RSS 对读者意味着什么\n- 如何让 archive 更好用`,
    start_at: '2026-04-25T12:00:00.000Z',
    end_at: '2026-04-25T13:30:00.000Z',
    location: 'Online',
    venue: 'Zoom / Telegram voice',
    city: 'online',
    registration_url: null,
    registration_note: '报名方式将在活动前一周公布。',
    cover_image_url: null,
    tags: ['online', 'editorial', 'geekdaily'],
  },
  {
    slug: 'community-media-retrospective',
    status: 'published',
    event_status: 'past',
    title: 'Community Media Retrospective',
    summary: '一次回顾社区内容系统、活动机制和协作方式的复盘讨论。',
    content: `## 我们复盘什么\n\n这场活动会回顾过去半年里 Rebase 社区的写作、招聘、活动和 GeekDaily 的变化。`,
    start_at: '2026-03-10T11:00:00.000Z',
    end_at: '2026-03-10T13:00:00.000Z',
    location: 'Hangzhou',
    venue: 'Riverside meetup room',
    city: 'hangzhou',
    registration_url: null,
    registration_note: '本场活动已结束。',
    cover_image_url: null,
    tags: ['retrospective', 'offline'],
  },
];

export const contributors = [
  {
    slug: 'ruix',
    status: 'published',
    name: 'Ruix',
    avatar_url: null,
    avatar_seed: 'ruix',
    headline: 'community steward',
    bio: '负责社区网站、信息架构和长期内容组织。',
    role_slugs: ['volunteers'],
    twitter_url: 'https://x.com/ruix',
    wechat: null,
    telegram: '@ruix',
  },
  {
    slug: 'cedric',
    status: 'published',
    name: 'Cedric',
    avatar_url: null,
    avatar_seed: 'cedric',
    headline: 'research curator',
    bio: '长期关注 protocol tooling 和 AI infrastructure。',
    role_slugs: ['geekdaily-advisors'],
    twitter_url: 'https://x.com/cedric',
    wechat: null,
    telegram: null,
  },
  {
    slug: 'harry',
    status: 'published',
    name: 'Harry',
    avatar_url: null,
    avatar_seed: 'harry',
    headline: 'editor and signal hunter',
    bio: '负责跟进市场、研究和日报中的高质量线索。',
    role_slugs: ['volunteers', 'geekdaily-advisors'],
    twitter_url: null,
    wechat: 'harry-rebase',
    telegram: null,
  },
  {
    slug: 'annie',
    status: 'published',
    name: 'Annie',
    avatar_url: null,
    avatar_seed: 'annie',
    headline: 'community producer',
    bio: '参与活动组织、投稿协调和合作伙伴沟通。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: '@annie_rebase',
  },
  {
    slug: 'test-volunteer-01',
    status: 'published',
    name: 'test volunteer 01',
    avatar_url: null,
    avatar_seed: 'test-volunteer-01',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-02',
    status: 'published',
    name: 'test volunteer 02',
    avatar_url: null,
    avatar_seed: 'test-volunteer-02',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-03',
    status: 'published',
    name: 'test volunteer 03',
    avatar_url: null,
    avatar_seed: 'test-volunteer-03',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-04',
    status: 'published',
    name: 'test volunteer 04',
    avatar_url: null,
    avatar_seed: 'test-volunteer-04',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-05',
    status: 'published',
    name: 'test volunteer 05',
    avatar_url: null,
    avatar_seed: 'test-volunteer-05',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-06',
    status: 'published',
    name: 'test volunteer 06',
    avatar_url: null,
    avatar_seed: 'test-volunteer-06',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-07',
    status: 'published',
    name: 'test volunteer 07',
    avatar_url: null,
    avatar_seed: 'test-volunteer-07',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-08',
    status: 'published',
    name: 'test volunteer 08',
    avatar_url: null,
    avatar_seed: 'test-volunteer-08',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-09',
    status: 'published',
    name: 'test volunteer 09',
    avatar_url: null,
    avatar_seed: 'test-volunteer-09',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-10',
    status: 'published',
    name: 'test volunteer 10',
    avatar_url: null,
    avatar_seed: 'test-volunteer-10',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
];
