export const siteSettings = {
  id: 1,
  site_name: 'Rebase',
  tagline: '由中国开发者业余时间共同建立的非营利开发者社区',
  description:
    'Rebase Community 是由中国开发者们在业余时间用热爱建立的非营利、公益性开发者社区，持续组织 GeekDaily、Who-Is-Hiring、活动、文章与协作项目。',
  primary_domain: 'https://rebase.network',
  secondary_domain: 'https://rebase.community',
  media_domain: 'https://media.rebase.network',
  hero_title: 'Rebase Community 是由中国开发者们在业余时间用热爱建立的开发者社区。',
  hero_summary:
    '我们是非营利、公益性的开发者社区，持续组织 GeekDaily、Who-Is-Hiring、活动、文章与协作项目，让社区交流、机会与长期记录都有稳定入口。',
  hero_primary_cta_label: '进入 GeekDaily',
  hero_primary_cta_url: '/geekdaily',
  hero_secondary_cta_label: '查看招聘板',
  hero_secondary_cta_url: '/who-is-hiring',
  social_links: [
    { label: 'B 站', href: 'https://space.bilibili.com/382886213' },
    { label: 'YouTube', href: 'https://www.youtube.com/@rebasecommunity' },
    { label: 'Discord', href: 'https://discord.gg/9BATkxjfXS' },
    { label: 'Twitter', href: 'https://x.com/RebaseCommunity', handle: '@RebaseCommunity' },
    { label: 'Telegram', href: 'https://t.me/rebasenetwork', handle: '@rebasenetwork' },
    { label: 'GitHub', href: 'https://github.com/rebase-network' },
    { label: '微信公众号', href: 'https://mp.weixin.qq.com/', handle: 'rebase_network' },
    { label: 'QQ 群', href: 'https://qm.qq.com/', handle: '1001507060' },
  ],
  footer_groups: [
    {
      title: '社区项目',
      slug: 'community-projects',
      links: [
        { label: 'Web3Camp', href: 'https://web3camp.us' },
        { label: 'Rebase D. Ventures', href: 'https://rebased.ventures' },
        { label: 'Rebase Hackathon', href: 'https://github.com/rebase-network/work-groups/blob/main/README.md#rebase-hackathon' },
        { label: 'Web3 极客日报', href: 'https://github.com/rebase-network/work-groups/blob/main/README.md#web3极客日报' },
        { label: 'Who is hiring', href: 'https://github.com/rebase-network/who-is-hiring' },
        { label: 'Event Pool', href: 'https://github.com/rebase-network/event-pool' },
        { label: '社区福利', href: 'https://github.com/rebase-network/benefits' },
      ],
    },
    {
      title: '站点入口',
      slug: 'site-entry',
      links: [
        { label: 'About Rebase', href: '/about' },
        { label: 'GeekDaily', href: '/geekdaily' },
        { label: 'Articles', href: '/articles' },
        { label: 'Who-Is-Hiring', href: '/who-is-hiring' },
        { label: 'Events', href: '/events' },
        { label: 'Contributors', href: '/contributors' },
        { label: 'RSS', href: '/rss.xml' },
      ],
    },
    {
      title: '社区渠道',
      slug: 'community-channels',
      links: [
        { label: 'B 站', href: 'https://space.bilibili.com/382886213' },
        { label: 'YouTube', href: 'https://www.youtube.com/@rebasecommunity' },
        { label: 'Discord', href: 'https://discord.gg/9BATkxjfXS' },
        { label: 'Twitter', href: 'https://x.com/RebaseCommunity' },
        { label: 'Telegram', href: 'https://t.me/rebasenetwork' },
      ],
    },
    {
      title: '协作与资源',
      slug: 'resources',
      links: [
        { label: '协作文档', href: 'https://shimo.im/space/loqeMGmL7wiMgvqn' },
        { label: '媒体资源', href: 'https://github.com/rebase-network/media-kit' },
        { label: 'GitHub', href: 'https://github.com/rebase-network' },
        { label: '社区网站', href: 'https://rebase.network' },
      ],
    },
  ],
  home_stats: [
    { value: '1809+', label: '极客日报期数' },
    { value: '5458+', label: '极客日报推荐条目' },
    { value: '7', label: '长期协作栏目' },
  ],
  copyright_text: 'Copyright © Rebase Community. All rights reserved.',
};

export const aboutPage = {
  id: 1,
  title: 'Rebase Community 是由中国开发者们在业余时间用热爱建立的开发者社区。',
  summary:
    'Rebase Community 是非营利、公益性的开发者社区，专注于技术交流，并持续通过多个栏目和协作板块为开发者提供交流、发布与连接的场所。',
  sections: [
    {
      title: '我们是谁',
      body:
        'Rebase Community 是由中国开发者们在业余时间用热爱建立的开发者社区。\n\n我们坚持非营利、公益性的社区方向，专注技术交流，并希望把社区中的内容、协作和机会组织成长期可访问的公共入口。',
    },
    {
      title: '社区栏目与项目',
      body:
        '- [Web3Camp](https://web3camp.us)\n- [Rebase D. Ventures](https://rebased.ventures)\n- [Rebase Hackathon](https://github.com/rebase-network/work-groups/blob/main/README.md#rebase-hackathon)\n- [Web3 极客日报](https://github.com/rebase-network/work-groups/blob/main/README.md#web3极客日报)\n- [Who is hiring](https://github.com/rebase-network/who-is-hiring)\n- [Event Pool](https://github.com/rebase-network/event-pool)\n- [社区福利](https://github.com/rebase-network/benefits)',
    },
    {
      title: '社区入口与联系',
      body:
        '- 网站：https://rebase.network\n- B 站：https://space.bilibili.com/382886213\n- YouTube：https://www.youtube.com/@rebasecommunity\n- 微信公众号：**rebase_network**\n- QQ 群：**1001507060**\n- [Discord](https://discord.gg/9BATkxjfXS)\n- [Twitter](https://x.com/RebaseCommunity)\n- [Telegram](https://t.me/rebasenetwork)\n- [协作文档](https://shimo.im/space/loqeMGmL7wiMgvqn)\n- [媒体资源](https://github.com/rebase-network/media-kit)',
    },
    {
      title: '捐赠支持',
      body:
        'Rebase 社区当前接受捐赠，多签地址如下：\n\n- Ethereum：`0xC8ecB38d26205BCeec31310806FA5e29F7426ADb`\n- Polygon：`0x843BF7AdEbCe362a9Dbb42a8bD460f4bE0f6ccBD`',
    },
  ],
};

export const contributorRoles = [
  {
    slug: 'volunteers',
    status: 'published',
    name: '志愿者',
    description: '推动活动、内容和社区协调工作的人。',
  },
  {
    slug: 'geekdaily-advisors',
    status: 'published',
    name: '极客日报智囊团',
    description: '持续提供选题、推荐和行业感知的朋友们。',
  },
];

export const articles = [
  {
    slug: 'building-rebase-in-public',
    status: 'published',
    title: '把 Rebase 做成一个持续更新的社区媒体站点',
    summary: '为什么我们不只想做一个静态官网，而是想把社区日常真正组织成可阅读、可订阅、可回看的公共空间。',
    body: `## 重新定义社区站点\n\n传统社区官网往往更像公告栏，而不是一个持续更新的信息场。\n\nRebase 新站希望把 **GeekDaily、文章、活动、招聘、贡献者** 放到同一个阅读流里，让读者能在一次访问中看到社区最近发生了什么。\n\n## 为什么要重做\n\n- 旧结构无法很好承接持续更新的内容\n- GeekDaily 的历史规模已经足够大，需要新的信息架构\n- Who-Is-Hiring 需要比 issue 更稳定的公开落点\n\n## 我们想保留什么\n\n我们并不是想把社区变成一套复杂产品，而是想让内容更容易发现、传播与回看。`,
    published_at: '2026-04-05T10:00:00.000Z',
    reading_time: '7 min read',
    authors: [{ name: 'Ruix', role: 'Community steward' }],
    tags: ['community', 'product', 'media'],
    cover_image_url: null,
    cover_accent: 'linear-gradient(135deg, #efc37b 0%, #0f766e 100%)',
  },
  {
    slug: 'signal-over-noise',
    status: 'published',
    title: '社区信息不是越多越好，而是越有组织越好',
    summary: '在高频更新的内容环境里，真正重要的是信息架构，而不是堆更多入口。',
    body: `## Signal over noise\n\n社区运营并不是简单地发布更多内容，而是把内容组织成可以连续阅读的结构。\n\n当一个网站同时承接文章、招聘、活动和日报时，首页应该扮演 **signal desk** 的角色。\n\n## 一个好首页的标准\n\n1. 让新读者在 10 秒内理解 Rebase 是什么\n2. 让老读者快速看到今天的变化\n3. 让运营同学不需要手动维护太多重复内容`,
    published_at: '2026-04-02T08:30:00.000Z',
    reading_time: '5 min read',
    authors: [{ name: 'Cedric', role: 'Contributor' }],
    tags: ['information architecture', 'editorial'],
    cover_image_url: null,
    cover_accent: 'linear-gradient(135deg, #f7b267 0%, #f4845f 100%)',
  },
  {
    slug: 'community-archives-should-stay-readable',
    status: 'published',
    title: '社区档案不该只存在于 issue 和聊天记录里',
    summary: '当内容积累到一定规模，归档、搜索和订阅就不再是“加分项”，而是基础设施。',
    body: `## 档案感\n\n很多社区都拥有大量高质量内容，但这些内容往往缺乏统一的入口。\n\nRebase 新站会把历史 GeekDaily、公开文章和招聘信息重新组织成可搜索、可浏览、可订阅的结构。\n\n## 这意味着什么\n\n- URL 需要稳定\n- 搜索需要可用\n- RSS 需要成为标准输出\n- 旧内容也应该被新的访问者看见`,
    published_at: '2026-03-28T12:00:00.000Z',
    reading_time: '6 min read',
    authors: [{ name: 'Harry', role: 'Editor' }],
    tags: ['archives', 'rss', 'search'],
    cover_image_url: null,
    cover_accent: 'linear-gradient(135deg, #5cc8ff 0%, #4361ee 100%)',
  },
];

const additionalTestJobs = [
  {
    slug: 'devrel-program-manager',
    company_name: 'Open Builders Guild',
    role_title: 'devrel program manager',
    salary: '$4,000 - $6,500 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / asia preferred',
    summary: '负责开发者沟通、线上活动和技术内容分发节奏，让生态更新被更多 builder 看见。',
    description: `## 岗位说明\n\n你会处在产品、开发者关系和社区协作的交叉位置，负责把对外沟通和开发者支持节奏稳定下来。\n\n## 你会参与\n\n- 维护开发者活动和线上分享节奏\n- 与产品和工程团队同步 roadmap 变化\n- 把复杂功能整理成更容易理解的技术内容\n\n## 我们看重\n\n你需要有清晰表达能力，也愿意持续跟踪开发者真实反馈。`,
    apply_url: 'https://example.com/jobs/devrel-program-manager',
    apply_note: '请附上你做过的技术内容、活动或开发者社区案例。',
    contact_label: 'telegram',
    contact_value: '@rebase_jobs_01',
    published_at: '2026-04-10T08:30:00.000Z',
    expires_at: '2026-05-12T15:59:59.999Z',
    tags: ['devrel', 'community', 'remote'],
  },
  {
    slug: 'smart-contract-engineer-defi',
    company_name: 'Harbor Labs',
    role_title: 'smart contract engineer',
    salary: '$6,500 - $10,000 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / shenzhen friendly',
    summary: '参与 DeFi 协议核心合约的开发、测试和上线流程，协同研究与审计团队推进版本发布。',
    description: `## 岗位说明\n\n我们正在扩展协议的交易、清算和风控模块，希望找到熟悉 Solidity 和测试体系的工程师一起推进。\n\n## 你会参与\n\n- 开发和维护协议核心合约\n- 编写测试并参与审计整改\n- 与前端和研究同学协作定义接口\n\n## 我们看重\n\n你需要对合约安全保持足够敏感，也愿意写出可维护的测试和文档。`,
    apply_url: 'https://example.com/jobs/smart-contract-engineer-defi',
    apply_note: '请附上公开仓库、审计经验或代表性合约项目。',
    contact_label: 'email',
    contact_value: 'jobs+solidity@example.com',
    published_at: '2026-04-09T09:30:00.000Z',
    expires_at: '2026-05-20T15:59:59.999Z',
    tags: ['solidity', 'defi', 'security'],
  },
  {
    slug: 'community-operations-coordinator',
    company_name: 'Layer East',
    role_title: 'community operations coordinator',
    salary: '$2,800 - $4,200 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / china time zone',
    summary: '维护社区日常运营节奏，整理协作信息、活动反馈和成员问题，让公共沟通更顺畅。',
    description: `## 岗位说明\n\n这个角色会连接社区成员、内容栏目和活动流程，保证社区运营不是零散响应，而是有节奏地推进。\n\n## 你会参与\n\n- 维护社群日常答疑和资料整理\n- 协调活动前后的执行细节\n- 跟进社区成员的反馈与需求\n\n## 我们看重\n\n你需要细致、稳定，并且能把混乱信息整理成大家都能继续协作的结构。`,
    apply_url: 'https://example.com/jobs/community-operations-coordinator',
    apply_note: '欢迎附上你参与过的社群运营、活动执行或项目协作经历。',
    contact_label: 'wechat',
    contact_value: 'rebase-ops',
    published_at: '2026-04-08T07:45:00.000Z',
    expires_at: '2026-05-08T15:59:59.999Z',
    tags: ['operations', 'community', 'coordination'],
  },
  {
    slug: 'protocol-research-analyst',
    company_name: 'Northstar Research',
    role_title: 'protocol research analyst',
    salary: '$4,500 - $7,000 / month',
    supports_remote: true,
    work_mode: 'part-time',
    location: 'remote',
    summary: '围绕协议设计、治理变化和市场结构整理研究简报，为产品、内容和 BD 提供长期输入。',
    description: `## 岗位说明\n\n你会负责持续追踪协议、生态和市场的变化，把碎片信号整理成有判断价值的研究材料。\n\n## 你会参与\n\n- 产出协议研究 memo 和简报\n- 跟踪竞品、治理和市场变化\n- 为内容和 BD 提供背景材料\n\n## 我们看重\n\n你需要有扎实的信息整理能力，也愿意用清楚的结构表达复杂结论。`,
    apply_url: 'https://example.com/jobs/protocol-research-analyst',
    apply_note: '请附上研究文章、报告或公开 thread 样本。',
    contact_label: 'telegram',
    contact_value: '@rebase_jobs_04',
    published_at: '2026-04-07T06:50:00.000Z',
    expires_at: null,
    tags: ['research', 'analysis', 'remote'],
  },
  {
    slug: 'technical-writer-open-source',
    company_name: 'Compose Stack',
    role_title: 'technical writer',
    salary: '$3,500 - $5,500 / month',
    supports_remote: true,
    work_mode: 'contract',
    location: 'remote',
    summary: '把产品文档、教程和版本更新写得更清楚，让开发者更快理解并上手使用。',
    description: `## 岗位说明\n\n我们需要一位能理解工程语境、同时也能写出清晰文档的技术写作者，帮助产品降低理解成本。\n\n## 你会参与\n\n- 维护产品文档和快速上手教程\n- 整理版本更新和迁移说明\n- 与工程师配合打磨示例和文档结构\n\n## 我们看重\n\n你需要兼顾准确性和可读性，不只是把信息堆进去。`,
    apply_url: 'https://example.com/jobs/technical-writer-open-source',
    apply_note: '请附上你的文档、教程或技术写作样本。',
    contact_label: 'email',
    contact_value: 'docs@example.com',
    published_at: '2026-04-06T05:40:00.000Z',
    expires_at: '2026-05-18T15:59:59.999Z',
    tags: ['documentation', 'writing', 'open-source'],
  },
  {
    slug: 'ecosystem-partnerships-lead',
    company_name: 'Chain Harbor',
    role_title: 'ecosystem partnerships lead',
    salary: '$5,500 - $8,000 / month',
    supports_remote: false,
    work_mode: 'full-time',
    location: 'singapore / hybrid',
    summary: '负责生态合作、合作伙伴关系跟进和联合活动策划，把生态连接真正落到执行层面。',
    description: `## 岗位说明\n\n你会与生态项目、媒体和活动伙伴保持长期沟通，把合作从一次性曝光变成持续协作。\n\n## 你会参与\n\n- 跟进潜在合作伙伴和联合计划\n- 协调内容、活动和合作节奏\n- 管理合作 pipeline 和复盘材料\n\n## 我们看重\n\n你需要能建立信任，也能把合作细节和推进状态维护得非常清楚。`,
    apply_url: 'https://example.com/jobs/ecosystem-partnerships-lead',
    apply_note: '请附上你做过的合作案例或生态拓展项目。',
    contact_label: 'telegram',
    contact_value: '@rebase_jobs_06',
    published_at: '2026-04-05T09:15:00.000Z',
    expires_at: '2026-05-15T15:59:59.999Z',
    tags: ['partnerships', 'ecosystem', 'hybrid'],
  },
  {
    slug: 'product-designer-data-tools',
    company_name: 'Signal Foundry',
    role_title: 'product designer',
    salary: '$4,200 - $6,800 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / beijing friendly',
    summary: '负责数据产品和内容工具的体验设计，把复杂信息变成更容易理解和操作的界面。',
    description: `## 岗位说明\n\n你会在数据视图、编辑工具和信息架构之间来回工作，持续优化复杂产品的可读性和可操作性。\n\n## 你会参与\n\n- 设计数据面板和内容编辑体验\n- 梳理信息架构和交互流程\n- 与前端一起打磨细节与落地效果\n\n## 我们看重\n\n你需要有系统思维，也愿意关心实现成本和真实使用场景。`,
    apply_url: 'https://example.com/jobs/product-designer-data-tools',
    apply_note: '请附上 portfolio 或你主导过的数据产品案例。',
    contact_label: 'wechat',
    contact_value: 'rebase-design',
    published_at: '2026-04-04T11:10:00.000Z',
    expires_at: null,
    tags: ['design', 'product', 'data'],
  },
  {
    slug: 'growth-content-strategist',
    company_name: 'Public Narrative',
    role_title: 'growth content strategist',
    salary: '$3,800 - $5,800 / month',
    supports_remote: true,
    work_mode: 'part-time',
    location: 'remote',
    summary: '围绕社区增长、专题内容和分发机制制定内容策略，让增长动作不再依赖临时发挥。',
    description: `## 岗位说明\n\n这个角色会和编辑、运营、活动协作，把内容从单次发布升级成稳定的增长与留存机制。\n\n## 你会参与\n\n- 制定专题与分发节奏\n- 设计内容增长实验和复盘方式\n- 与运营协同优化渠道表现\n\n## 我们看重\n\n你需要同时理解内容、分发和社区语境，而不是只会写标题。`,
    apply_url: 'https://example.com/jobs/growth-content-strategist',
    apply_note: '欢迎附上 newsletter、专题栏目或增长实验案例。',
    contact_label: 'email',
    contact_value: 'growth@example.com',
    published_at: '2026-04-03T10:20:00.000Z',
    expires_at: '2026-05-09T15:59:59.999Z',
    tags: ['growth', 'content', 'strategy'],
  },
  {
    slug: 'event-producer-builder-program',
    company_name: 'Merge Collective',
    role_title: 'event producer',
    salary: '$3,200 - $4,800 / month',
    supports_remote: false,
    work_mode: 'contract',
    location: 'shanghai / onsite as needed',
    summary: '负责 builder 活动项目的策划与执行，把议程、嘉宾、场地和协作流程真正落地。',
    description: `## 岗位说明\n\n你会负责活动执行的关键节点，让线下活动不只是发布海报，而是有完整体验和清晰协作的项目。\n\n## 你会参与\n\n- 推进活动议程、嘉宾与场地安排\n- 维护活动执行清单与时间表\n- 协调合作方、摄影和现场志愿者\n\n## 我们看重\n\n你需要有较强执行力，也能在复杂现场里保持清楚判断。`,
    apply_url: 'https://example.com/jobs/event-producer-builder-program',
    apply_note: '请附上你参与过的活动策划或执行案例。',
    contact_label: 'telegram',
    contact_value: '@rebase_jobs_09',
    published_at: '2026-04-02T08:55:00.000Z',
    expires_at: '2026-04-30T15:59:59.999Z',
    tags: ['events', 'production', 'onsite'],
  },
  {
    slug: 'data-engineer-community-analytics',
    company_name: 'Atlas Community Lab',
    role_title: 'data engineer',
    salary: '$5,500 - $8,200 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / utc+8 overlap',
    summary: '搭建社区分析和内容归档的数据链路，让内容、活动和招聘数据能够被稳定查询和复用。',
    description: `## 岗位说明\n\n你会负责把分散在多个来源里的社区数据整理到可维护的数据模型和分析流程中。\n\n## 你会参与\n\n- 设计内容与活动数据同步链路\n- 维护分析表和查询接口\n- 支持搜索、归档和统计模块\n\n## 我们看重\n\n你需要能兼顾数据正确性、维护成本和后续产品使用场景。`,
    apply_url: 'https://example.com/jobs/data-engineer-community-analytics',
    apply_note: '请附上数据工程、ETL 或分析平台相关案例。',
    contact_label: 'email',
    contact_value: 'data@example.com',
    published_at: '2026-04-01T07:25:00.000Z',
    expires_at: '2026-05-22T15:59:59.999Z',
    tags: ['data', 'analytics', 'backend'],
  },
];

export const jobs = [
  {
    slug: 'protocol-growth-lead',
    status: 'published',
    company_name: 'Open Protocol Studio',
    role_title: 'protocol growth lead',
    salary: '$4,500 - $7,500 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / shanghai friendly',
    summary: '寻找熟悉开发者社区、内容运营和 protocol narrative 的增长负责人。',
    description: `## 岗位说明\n\n我们希望你能够在协议团队、开发者社区和内容传播之间建立顺畅协作。\n\n## 你会负责\n\n- 设计增长叙事\n- 对接活动与合作伙伴\n- 搭建长期内容分发节奏\n- 推动协议与社区叙事协同\n- 维护内容节奏和活动节奏\n- 与研究、开发和设计角色共同工作`,
    apply_url: 'https://example.com/jobs/protocol-growth-lead',
    apply_note: '请附上你主导过的社区、内容或增长案例。',
    contact_label: 'telegram',
    contact_value: '@rebase_hiring',
    published_at: '2026-04-04T09:00:00.000Z',
    expires_at: null,
    tags: ['growth', 'community', 'remote'],
  },
  {
    slug: 'community-editor',
    status: 'published',
    company_name: 'Builder Commons',
    role_title: 'community editor',
    salary: '$3,000 - $5,000 / month',
    supports_remote: true,
    work_mode: 'part-time',
    location: 'remote',
    summary: '负责社区写作、日报编排和专题策划，让内容从“发布”变成“持续阅读”。',
    description: `## 我们想找的人\n\n你不一定是专业媒体编辑，但需要对技术社区有长期观察，也愿意把复杂信息整理得更易读。\n\n## 方向\n\n- 日报整理\n- 专题写作\n- 站点栏目维护\n- 编辑文章与日报\n- 协调投稿与栏目排期\n- 优化内容展示和订阅体验`,
    apply_url: 'https://example.com/jobs/community-editor',
    apply_note: '欢迎附上你的文章、newsletter 或公开写作样本。',
    contact_label: 'email',
    contact_value: 'jobs@rebase.network',
    published_at: '2026-04-01T08:00:00.000Z',
    expires_at: null,
    tags: ['editorial', 'media', 'remote'],
  },
  {
    slug: 'frontend-engineer-community-platform',
    status: 'published',
    company_name: 'Rebase Studio',
    role_title: 'frontend engineer',
    salary: '$5,000 - $8,500 / month',
    supports_remote: true,
    work_mode: 'full-time',
    location: 'remote / china time zone preferred',
    summary: '负责社区站点、内容产品和数据展示模块的前端实现。',
    description: `## 你会参与\n\n- 社区网站体验优化\n- 内容系统前台实现\n- 搜索、订阅和信息归档模块\n- 实现 Astro 前端体验\n- 协同 CMS 数据接入\n- 完善测试与发布流程\n\n## 我们看重\n\n对 UI 细节、信息组织和前端工程质量的平衡能力。`,
    apply_url: 'https://example.com/jobs/frontend-engineer-community-platform',
    apply_note: '请附上你主导或深度参与过的前端项目。',
    contact_label: 'wechat',
    contact_value: 'rebase-jobs',
    published_at: '2026-03-30T10:00:00.000Z',
    expires_at: null,
    tags: ['frontend', 'astro', 'community'],
  },
  ...additionalTestJobs.map((job) => ({
    ...job,
    status: 'published',
  })),
];

export const additionalTestEvents = [
  {
    slug: 'rebase-guangzhou-maintainer-breakfast',
    event_status: 'upcoming',
    title: 'Rebase Guangzhou Maintainer Breakfast',
    summary: '围绕社区维护、开源协作和内容分发节奏做一场更轻量的早餐碰头。',
    content:
      '## 活动内容\n\n我们会围绕社区维护、写作节奏和开源协作方式做一次小范围交流。\n\n## 适合谁来\n\n- maintainer\n- volunteer\n- 对社区运营感兴趣的人',
    start_at: '2026-04-22T01:00:00.000Z',
    end_at: '2026-04-22T03:00:00.000Z',
    location: 'Guangzhou',
    venue: 'Tianhe breakfast club',
    city: 'guangzhou',
    registration_url: 'https://example.com/events/rebase-guangzhou-maintainer-breakfast',
    cover_image_url: null,
    tags: ['offline', 'maintainer', 'guangzhou'],
  },
  {
    slug: 'rebase-beijing-protocol-reading-room',
    event_status: 'upcoming',
    title: 'Rebase Beijing Protocol Reading Room',
    summary: '一起读一篇 protocol research，顺手讨论它如何影响社区的长期内容栏目。',
    content:
      '## 活动内容\n\n我们会选一篇协议研究文章做阅读和讨论。\n\n## 适合谁来\n\n- researcher\n- editor\n- 对 protocol design 感兴趣的人',
    start_at: '2026-04-29T11:00:00.000Z',
    end_at: '2026-04-29T13:00:00.000Z',
    location: 'Beijing',
    venue: 'Chaoyang reading room',
    city: 'beijing',
    registration_url: null,
    cover_image_url: null,
    tags: ['offline', 'research', 'beijing'],
  },
  {
    slug: 'rebase-remote-operator-clinic',
    event_status: 'upcoming',
    title: 'Rebase Remote Operator Clinic',
    summary: '面向社区运营和内容维护人员的线上问答时段，集中讨论后台工作流和协作问题。',
    content:
      '## 活动内容\n\n集中讨论站点编辑、内容维护和协作节奏。\n\n## 适合谁来\n\n- operator\n- editor\n- staff',
    start_at: '2026-05-06T12:00:00.000Z',
    end_at: '2026-05-06T13:30:00.000Z',
    location: 'Online',
    venue: 'Zoom',
    city: 'online',
    registration_url: 'https://example.com/events/rebase-remote-operator-clinic',
    cover_image_url: null,
    tags: ['online', 'operator', 'workflow'],
  },
  {
    slug: 'rebase-shenzhen-ai-tooling-demo-night',
    event_status: 'upcoming',
    title: 'Rebase Shenzhen AI Tooling Demo Night',
    summary: '给社区里的 builder 一个更轻量的 demo 场，分享最近做的 AI tooling 和自动化工具。',
    content:
      '## 活动内容\n\n每位分享者有 10 分钟展示一个最近完成的工具或原型。\n\n## 适合谁来\n\n- builder\n- frontend engineer\n- ai tooling maker',
    start_at: '2026-05-13T11:30:00.000Z',
    end_at: '2026-05-13T14:00:00.000Z',
    location: 'Shenzhen',
    venue: 'Nanshan maker lounge',
    city: 'shenzhen',
    registration_url: 'https://example.com/events/rebase-shenzhen-ai-tooling-demo-night',
    cover_image_url: null,
    tags: ['offline', 'ai', 'shenzhen'],
  },
  {
    slug: 'rebase-community-rss-lab',
    event_status: 'upcoming',
    title: 'Rebase Community RSS Lab',
    summary: '一次围绕 RSS、订阅体验和长期归档结构的线上实验室讨论。',
    content:
      '## 活动内容\n\n我们会一起讨论 RSS、信息分发与 archive 设计。\n\n## 适合谁来\n\n- editor\n- rss reader\n- archive nerd',
    start_at: '2026-05-20T12:30:00.000Z',
    end_at: '2026-05-20T14:00:00.000Z',
    location: 'Online',
    venue: 'Telegram voice',
    city: 'online',
    registration_url: null,
    cover_image_url: null,
    tags: ['online', 'rss', 'archive'],
  },
  {
    slug: 'rebase-hangzhou-editorial-review-salon',
    event_status: 'upcoming',
    title: 'Rebase Hangzhou Editorial Review Salon',
    summary: '针对文章、日报和活动文案做一次面对面的编辑复盘和改稿练习。',
    content:
      '## 活动内容\n\n围绕内容结构、标题、摘要和页面编排做一次线下 review。\n\n## 适合谁来\n\n- editor\n- volunteer\n- content curator',
    start_at: '2026-05-27T10:30:00.000Z',
    end_at: '2026-05-27T13:00:00.000Z',
    location: 'Hangzhou',
    venue: 'Canal side studio',
    city: 'hangzhou',
    registration_url: 'https://example.com/events/rebase-hangzhou-editorial-review-salon',
    cover_image_url: null,
    tags: ['offline', 'editorial', 'hangzhou'],
  },
  {
    slug: 'rebase-archive-rebuild-retrospective',
    event_status: 'past',
    title: 'Rebase Archive Rebuild Retrospective',
    summary: '一次围绕历史内容迁移、结构化字段和公开站点归档方式的复盘会。',
    content:
      '## 我们复盘什么\n\n重点回顾 archive 重构、数据迁移和内容组织过程中踩过的坑。',
    start_at: '2026-03-26T11:00:00.000Z',
    end_at: '2026-03-26T13:00:00.000Z',
    location: 'Shanghai',
    venue: 'Xuhui project room',
    city: 'shanghai',
    registration_url: null,
    cover_image_url: null,
    tags: ['retrospective', 'archive', 'offline'],
  },
  {
    slug: 'rebase-volunteer-onboarding-open-hour',
    event_status: 'past',
    title: 'Rebase Volunteer Onboarding Open Hour',
    summary: '给新加入的志愿者介绍社区栏目、工作方式和协作工具。',
    content:
      '## 活动内容\n\n集中介绍社区栏目、协作方式和日常节奏，帮助新志愿者快速上手。',
    start_at: '2026-03-19T12:00:00.000Z',
    end_at: '2026-03-19T13:30:00.000Z',
    location: 'Online',
    venue: 'Zoom',
    city: 'online',
    registration_url: null,
    cover_image_url: null,
    tags: ['onboarding', 'volunteer', 'online'],
  },
  {
    slug: 'rebase-open-source-writing-workshop',
    event_status: 'past',
    title: 'Rebase Open Source Writing Workshop',
    summary: '一次关于技术写作、社区文档和公开复盘方法的工作坊。',
    content:
      '## 活动内容\n\n一起拆解技术写作和社区写作的结构，讨论如何把复杂内容写得更可读。',
    start_at: '2026-03-05T10:00:00.000Z',
    end_at: '2026-03-05T12:30:00.000Z',
    location: 'Hangzhou',
    venue: 'West lake workshop room',
    city: 'hangzhou',
    registration_url: null,
    cover_image_url: null,
    tags: ['writing', 'workshop', 'offline'],
  },
  {
    slug: 'rebase-builder-tools-showcase',
    event_status: 'past',
    title: 'Rebase Builder Tools Showcase',
    summary: '给社区里的工具作者一个快速展示窗口，也顺带讨论这些工具如何进入长期栏目。',
    content:
      '## 活动内容\n\n每位作者用 8 分钟展示一个最近做的工具，并讨论其适合的公开发布方式。',
    start_at: '2026-02-20T11:30:00.000Z',
    end_at: '2026-02-20T14:00:00.000Z',
    location: 'Shenzhen',
    venue: 'Maker dock',
    city: 'shenzhen',
    registration_url: null,
    cover_image_url: null,
    tags: ['builder', 'tools', 'offline'],
  },
];

export const events = [
  {
    slug: 'rebase-shanghai-builder-night',
    status: 'published',
    event_status: 'upcoming',
    title: 'Rebase Shanghai Builder Night',
    summary: '一次围绕 AI tools、protocol research 和 community tooling 的小型夜间聚会。',
    content: `## 活动内容\n\n我们会邀请社区成员分享最近在做的工具、研究和协作方式。\n\n## 适合谁来\n\n- builder\n- editor\n- operator\n- 对社区产品感兴趣的人`,
    start_at: '2026-04-18T11:30:00.000Z',
    end_at: '2026-04-18T14:30:00.000Z',
    location: 'Shanghai',
    venue: 'West Bund community space',
    city: 'shanghai',
    registration_url: 'https://example.com/events/rebase-shanghai-builder-night',
    cover_image_url: null,
    tags: ['offline', 'builder', 'shanghai'],
  },
  {
    slug: 'geekdaily-editor-roundtable',
    status: 'published',
    event_status: 'upcoming',
    title: 'GeekDaily Editor Roundtable',
    summary: '围绕 GeekDaily 的选题、结构和订阅体验，做一次运营和编辑侧的公开讨论。',
    content: `## 讨论方向\n\n- 一期 GeekDaily 该如何被组织\n- 搜索和 RSS 对读者意味着什么\n- 如何让 archive 更好用`,
    start_at: '2026-04-25T12:00:00.000Z',
    end_at: '2026-04-25T13:30:00.000Z',
    location: 'Online',
    venue: 'Zoom / Telegram voice',
    city: 'online',
    registration_url: null,
    cover_image_url: null,
    tags: ['online', 'editorial', 'geekdaily'],
  },
  {
    slug: 'community-media-retrospective',
    status: 'published',
    event_status: 'past',
    title: 'Community Media Retrospective',
    summary: '一次回顾社区内容系统、活动机制和协作方式的复盘讨论。',
    content: `## 我们复盘什么\n\n这场活动会回顾过去半年里 Rebase 社区的写作、招聘、活动和 GeekDaily 的变化。`,
    start_at: '2026-03-10T11:00:00.000Z',
    end_at: '2026-03-10T13:00:00.000Z',
    location: 'Hangzhou',
    venue: 'Riverside meetup room',
    city: 'hangzhou',
    registration_url: null,
    cover_image_url: null,
    tags: ['retrospective', 'offline'],
  },
  ...additionalTestEvents.map((event) => ({
    ...event,
    status: 'published',
  })),
];

export const contributors = [
  {
    slug: 'ruix',
    status: 'published',
    name: 'Ruix',
    avatar_url: null,
    avatar_seed: 'ruix',
    headline: 'community steward',
    bio: '负责社区网站、信息架构和长期内容组织。',
    role_slugs: ['volunteers'],
    twitter_url: 'https://x.com/ruix',
    wechat: null,
    telegram: '@ruix',
  },
  {
    slug: 'cedric',
    status: 'published',
    name: 'Cedric',
    avatar_url: null,
    avatar_seed: 'cedric',
    headline: 'research curator',
    bio: '长期关注 protocol tooling 和 AI infrastructure。',
    role_slugs: ['geekdaily-advisors'],
    twitter_url: 'https://x.com/cedric',
    wechat: null,
    telegram: null,
  },
  {
    slug: 'harry',
    status: 'published',
    name: 'Harry',
    avatar_url: null,
    avatar_seed: 'harry',
    headline: 'editor and signal hunter',
    bio: '负责跟进市场、研究和日报中的高质量线索。',
    role_slugs: ['volunteers', 'geekdaily-advisors'],
    twitter_url: null,
    wechat: 'harry-rebase',
    telegram: null,
  },
  {
    slug: 'annie',
    status: 'published',
    name: 'Annie',
    avatar_url: null,
    avatar_seed: 'annie',
    headline: 'community producer',
    bio: '参与活动组织、投稿协调和合作伙伴沟通。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: '@annie_rebase',
  },
  {
    slug: 'test-volunteer-01',
    status: 'published',
    name: 'test volunteer 01',
    avatar_url: null,
    avatar_seed: 'test-volunteer-01',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-02',
    status: 'published',
    name: 'test volunteer 02',
    avatar_url: null,
    avatar_seed: 'test-volunteer-02',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-03',
    status: 'published',
    name: 'test volunteer 03',
    avatar_url: null,
    avatar_seed: 'test-volunteer-03',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-04',
    status: 'published',
    name: 'test volunteer 04',
    avatar_url: null,
    avatar_seed: 'test-volunteer-04',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-05',
    status: 'published',
    name: 'test volunteer 05',
    avatar_url: null,
    avatar_seed: 'test-volunteer-05',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-06',
    status: 'published',
    name: 'test volunteer 06',
    avatar_url: null,
    avatar_seed: 'test-volunteer-06',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-07',
    status: 'published',
    name: 'test volunteer 07',
    avatar_url: null,
    avatar_seed: 'test-volunteer-07',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-08',
    status: 'published',
    name: 'test volunteer 08',
    avatar_url: null,
    avatar_seed: 'test-volunteer-08',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-09',
    status: 'published',
    name: 'test volunteer 09',
    avatar_url: null,
    avatar_seed: 'test-volunteer-09',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
  {
    slug: 'test-volunteer-10',
    status: 'published',
    name: 'test volunteer 10',
    avatar_url: null,
    avatar_seed: 'test-volunteer-10',
    headline: 'community volunteer',
    bio: '用于验证首页贡献者群像布局的测试志愿者档案。',
    role_slugs: ['volunteers'],
    twitter_url: null,
    wechat: null,
    telegram: null,
  },
];
